### ISSUE TITLE
Assignment-1 Factorial

### ISSUE THREAD

**Issue by 57bit23** [vtcbca/basic-programming-56bit23#3]
What do you mean by factorial?

**Comment by 56bit23** [comment]
A factorial is a mathematical function that multiplies a positive integer by all the positive integers.

**Comment by 57bit23** [comment]
Not understand yet

**Comment by 60bit23** [comment]
its very simple, it is the multiplication of 1 to the inputed number given by user.

**Comment by 57bit23** [comment]
@60bit23 can you explain me in mathematical way?

**Comment by 60bit23** [comment]
yeah why not,
if you have to find the factorial of 7 then you should follow the following method.
7!=1*2*3*4*5*6*7

**Comment by 57bit23** [comment]
7!=1234567?

**Comment by 60bit23** [comment]
7!=7 × 6 × 5× 4 × 3 × 2 × 1

**Comment by 56bit23** [comment]
@60bit23 Exactly

**Comment by 57bit23** [comment]
ok now I've understood the Factorial

**Comment by 57bit23** [comment]
@60bit23 and @56bit23 thanks for your response
