### ISSUE TITLE
Assignment-2 Prime Number

### ISSUE THREAD

**Issue by 58bit23** [vtcbca/basic-programming-56bit23#4]
How to identify a prime number?

**Comment by 56bit23** [comment]
A number that can be divided exactly only by itself

**Comment by 58bit23** [comment]
What it mean exactly?

**Comment by 59bit23** [comment]
It means the number which cannot be divided by any other number except by itself.

**Comment by 56bit23** [comment]
Exactly and also with 1

**Comment by 58bit23** [comment]
@59bit23 can you just give some example

**Comment by 59bit23** [comment]
Yes here are some example
1,3,7,11

**Comment by 58bit23** [comment]
Can anyone give me some example

**Comment by 59bit23** [comment]
Yes here are some example
1,3,7,11,13

**Comment by 58bit23** [comment]
explain me in mathematical way

**Comment by 56bit23** [comment]
Yes
checking integer'7'
'7' can just divide with '1' and '7' but not divided by any other number

**Comment by 58bit23** [comment]
Ok I understood the Prime number
@56bit23 and @59bit23 Thank you for your response
