### ISSUE TITLE
assignment 3 Fibonacci sequence

### ISSUE THREAD

**Issue by 60bit23** [vtcbca/basic-programming-56bit23#5]
how do I get fibonacci sequence?

**Comment by 56bit23** [comment]
it is very easy
if the series starts with 0 and 1 then the third value will be the addition of 0 and 1, fourth value will be the addition of second and third values means 1+2.

**Comment by 60bit23** [comment]
Can i get a example?

**Comment by 56bit23** [comment]
yes here it is
0,1,1,2,3,5,8,13,21.......

**Comment by 60bit23** [comment]
What if the series starts with 2 and 3?

**Comment by 56bit23** [comment]
then it will goes like
2,3,5,8,13.........

**Comment by 60bit23** [comment]
What if the series starts with 4 and 5?

**Comment by 56bit23** [comment]
Then it will goes like
4,5,9,14,23....

**Comment by 60bit23** [comment]
My all doubts are clear now
Thanks @56bit23 for your response
