### ISSUE TITLE
assignment 4 Reverse String

### ISSUE THREAD

**Issue by 60bit23** [vtcbca/basic-programming-56bit23#6]
Where the string is used in python?

**Comment by 60bit23** [comment]
**Common Applications of Strings in Python**

1. User Input: Strings are used to handle user inputs, for example, reading names or passwords.
2. Text Processing: Strings are essential in manipulating, analyzing, and formatting text data.
3. File I/O: Strings are used when reading from or writing to files.
4. Web Development: In frameworks like Flask or Django, strings handle URL routes, templates, and responses.
5. Data Processing: Strings are used to handle data in CSV, JSON, and XML formats.

**Comment by 56bit23** [comment]
**Common Applications of Strings in Python**

1. User Input: Strings are used to handle user inputs, for example, reading names or passwords.
2. Text Processing: Strings are essential in manipulating, analyzing, and formatting text data.
3. File I/O: Strings are used when reading from or writing to files.
4. Web Development: In frameworks like Flask or Django, strings handle URL routes, templates, and responses.
5. Data Processing: Strings are used to handle data in CSV, JSON, and XML.

**Comment by 60bit23** [comment]
How many functions are related to string in python?

**Comment by 56bit23** [comment]
There are 40+ built-in string functions in Python.

**Comment by 60bit23** [comment]
Ok can you just give me some of the function with their use?

**Comment by 56bit23** [comment]
Yeah sure

**Comment by 56bit23** [comment]
Here are some functions
str.upper(): Converts all characters to uppercase.
str.lower(): Converts all characters to lowercase.
str.strip(): Removes leading and trailing whitespaces.
str.lstrip(): Removes leading whitespaces.
str.rstrip(): Removes trailing whitespaces.
str.isalnum(): Returns True if the string contains only alphanumeric characters.
str.isalpha(): Returns True if the string contains only alphabetic characters.
str.isdigit(): Returns True if the string contains only digits.

**Comment by 60bit23** [comment]
Thank you @56bit23 for your positive response.

**Comment by 56bit23** [comment]
Yes it was my pleasure.
